- name: varables at play level
  hosts: local
  vars:
    SCHOOL: "ZPHS High School"
    CLASS: "10TH CLASS"
    VILLAGE: "KIDIGAM"
  tasks:
    - name: printing content from variabs
      ansible.builtin.debug:
        msg: "i had studied at {{SCHOOL}} in class {{CLASS}} at village {{VILLAGE}}"


