- name: running the loops
  hosts: vs
  

  tasks:
    - name: install software
      become: true
      ansible.builtin.package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
      loop:
       - { name: 'nginx' ,state: 'present'}
       - { name: 'apache' ,state: 'absent'}
       - { name: 'mysql' ,state: 'present'}
       - { name: 'redis' ,state: 'absent'}