- name: running the loops
  hosts: local 
  connection: local

  tasks:
    - name: printing all roomates names in the list
      ansible.builtin.debug:
        msg: "Roomate name: {{ item }}"
        loop:
         - deepan
         - sreekar
         - naveen
         - vicky
         