- name: running the loops
  hosts: local 
  connection: local

  tasks:
    - name: printing all roomates names in the list
      ansible.builtin.package:
        - name: {{ item.name }}
        - state: {{ item.state }}
      loop:
       - { name: 'nginx' ,state: 'present'}
       - { name: 'apache' ,state: 'absent'}
       - { name: 'mysql' ,state: 'present'}
       - { name: 'redis' ,state: 'absent'}